services:
  db:
    image: mariadb:lts
    container_name: mariadb

    user: 1000:1000

    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

    restart: unless-stopped

    volumes:
      - ~/Containers-data/nextcloud-db:/var/lib/mysql:Z #https://stackoverflow.com/questions/35218194/what-is-the-z-flag-in-docker-containers-volumes-from-option

    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1

    env_file:
      - db.env

  app:
    image: nextcloud:apache
    container_name: nextcloud_apache

    user: 1000:1000

    ports:
      - 8082:80

    restart: unless-stopped

    volumes:
      - ~/Containers-data/nextcloud:/var/www/html:z

    environment:
     - MYSQL_HOST=db

    env_file:
      - db.env

    depends_on:
      - db

volumes:
  nextcloud:
  db:
