services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf

    ports:
      - "8081:8080"

    restart: unless-stopped

    volumes:
      - ~/Containers-data/stirling:/configs
