networks:
  frontend:

services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server

    networks:
      - frontend

    user: 1000:1000

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    command:
      - -m
      - ${MODEL}
      - --host
      - 0.0.0.0
      - --mlock
      - -t
      - "2"
      - -c
      - "4096"
      - -b
      - "256"

    ports:
      - "8080:8080"

    ulimits:
      memlock:
        soft: -1
        hard: -1

    restart: unless-stopped

    volumes:
      - ~/Containers-data/llama.cpp:/models:ro,Z
